/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.negozio;

import java.lang.reflect.Array;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luca
 */
public class NegozioForm extends javax.swing.JFrame {

    DefaultTableModel model_s, model_f, model_m, model_v;
    DB db = new DB();
    ArrayList<Prodotto> scontrino = new ArrayList<>();

    /**
     * Creates new form NegozioForm
     */
    public NegozioForm() throws SQLException {
        initComponents();
        model_s = (DefaultTableModel) table_scontrino.getModel();
        model_v = (DefaultTableModel) table_vendi.getModel();
        calcolo_totale();
        lista_fornitori();
        lista_magazzino();
        vendi_prodotto();
        estrai_qtprodotto();
    }

    private void calcolo_totale() {
        String nome = acquista_prodotto.getText();
        double qnt = Double.parseDouble(acquista_quantita.getText());
        double prezzo = Double.parseDouble(acquista_prezzo.getText());
        double totale = qnt * prezzo;
        String tot = "" + totale;
        acquista_totale.setText(tot);
    }

    private void lista_fornitori() throws SQLException {
        model_f = (DefaultTableModel) table_fornitori.getModel();
        ResultSet rs = db.fornitori();
        String nome = "", piva = "", indirizzo = "", citta = "", nazione = "";
        while (rs.next()) {
            nome = rs.getString("nome");
            piva = rs.getString("p_iva");
            indirizzo = rs.getString("indirizzo");
            citta = rs.getString("citta");
            nazione = rs.getString("nazione");
            String riga[] = {nome, piva, indirizzo, citta, nazione};
            model_f.addRow(riga);
        }
    }

    private void lista_magazzino() throws SQLException {
        model_m = (DefaultTableModel) table_magazzino.getModel();
        ResultSet rs = db.magazzino();
        String id = "", nome = "", qnt = "", prezzo = "", barcode = "";
        while (rs.next()) {
            id = "" + rs.getInt("id");
            nome = rs.getString("nome");
            qnt = "" + rs.getInt("quantita");
            prezzo = "" + rs.getDouble("prezzo");
            barcode = rs.getString("barcode");
            String riga[] = {id, nome, qnt, prezzo, barcode};
            model_m.addRow(riga);
        }
    }

    private void vendi_prodotto() {
        ResultSet rs = db.magazzino();
        try {
            while (rs.next()) {
                vendi_nome_prodotto.addItem(rs.getString("nome") + " (" + rs.getInt("quantita") + ")");;
            }
        } catch (SQLException ex) {
            Logger.getLogger(NegozioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void estrai_qtprodotto() {
        String nome = vendi_nome_prodotto.getSelectedItem().toString().substring(0, vendi_nome_prodotto.getSelectedItem().toString().indexOf("("));
        int x = db.estrai_qtprodotto(nome);
        box_qnt_vendi.removeAllItems();
        if(x > 0){
            for (int i = 1; i < x + 1; i++) {
                box_qnt_vendi.addItem("" + i);
            }
        }else{
            box_qnt_vendi.addItem("" + 0);
        }
        
    }

    private String calcolo_totale_vendi(int qnt) {
        String x = vendi_nome_prodotto.getSelectedItem().toString().substring(0, vendi_nome_prodotto.getSelectedItem().toString().indexOf("("));
        ResultSet rs = db.cerca_prodotto(x);
        String totale = "";
        double tmp = 0;
        try {
            while (rs.next()) {
                tmp = qnt * rs.getDouble("prezzo");
                totale = "" + tmp;
            }
        } catch (SQLException ex) {
            Logger.getLogger(NegozioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return totale;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu = new javax.swing.JTabbedPane();
        Vendi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vendi_totale = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_vendi = new javax.swing.JTable();
        vendi_button = new javax.swing.JButton();
        vendi_aggiungi = new javax.swing.JButton();
        vendi_storico = new javax.swing.JButton();
        vendi_nome_prodotto = new javax.swing.JComboBox<>();
        box_qnt_vendi = new javax.swing.JComboBox<>();
        Acquista = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        acquista_prezzo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        acquista_totale = new javax.swing.JTextField();
        acquista_prodotto = new javax.swing.JTextField();
        acquista_quantita = new javax.swing.JTextField();
        acquista_aggiungi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_scontrino = new javax.swing.JTable();
        acquista_button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        acquista_fornitore = new javax.swing.JComboBox<>();
        acquista_storico = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        acquista_barcode = new javax.swing.JTextField();
        Magazzino = new javax.swing.JPanel();
        mag_tabella = new javax.swing.JScrollPane();
        table_magazzino = new javax.swing.JTable();
        mag_cerca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mag_cercabarcode = new javax.swing.JTextField();
        Fornitori = new javax.swing.JPanel();
        forn_tabella = new javax.swing.JScrollPane();
        table_fornitori = new javax.swing.JTable();
        forn_cerca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_nuovofornitore = new javax.swing.JButton();
        btn_agg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Prodotto");

        jLabel2.setText("Quantità");

        jLabel4.setText("Totale");

        table_vendi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "prodotto", "quantità", "prezzo", "totale"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_vendi);

        vendi_button.setText("Vendi");
        vendi_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendi_buttonActionPerformed(evt);
            }
        });

        vendi_aggiungi.setText("Aggiungi");
        vendi_aggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendi_aggiungiActionPerformed(evt);
            }
        });

        vendi_storico.setText("Visualizza Storico Vendite");
        vendi_storico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendi_storicoActionPerformed(evt);
            }
        });

        vendi_nome_prodotto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        vendi_nome_prodotto.setMaximumRowCount(10);
        vendi_nome_prodotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendi_nome_prodottoActionPerformed(evt);
            }
        });

        box_qnt_vendi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_qnt_vendiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VendiLayout = new javax.swing.GroupLayout(Vendi);
        Vendi.setLayout(VendiLayout);
        VendiLayout.setHorizontalGroup(
            VendiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VendiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VendiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VendiLayout.createSequentialGroup()
                        .addGroup(VendiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vendi_nome_prodotto, 0, 200, Short.MAX_VALUE)
                            .addComponent(vendi_totale)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VendiLayout.createSequentialGroup()
                                .addComponent(vendi_aggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addComponent(box_qnt_vendi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 39, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VendiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(VendiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vendi_storico)
                            .addComponent(vendi_button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );
        VendiLayout.setVerticalGroup(
            VendiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vendi_storico)
                .addGap(13, 13, 13)
                .addGroup(VendiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendiLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vendi_button))
                    .addGroup(VendiLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vendi_nome_prodotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box_qnt_vendi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vendi_totale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(vendi_aggiungi)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        MainMenu.addTab("Vendi", Vendi);

        jLabel5.setText("Nome Prodotto");

        jLabel6.setText("Quantità");

        jLabel7.setText("Prezzo Unitario");

        acquista_prezzo.setText("0");
        acquista_prezzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acquista_prezzoActionPerformed(evt);
            }
        });
        acquista_prezzo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                acquista_prezzoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                acquista_prezzoKeyReleased(evt);
            }
        });

        jLabel8.setText("Totale");

        acquista_totale.setEditable(false);
        acquista_totale.setText("totale");

        acquista_prodotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acquista_prodottoActionPerformed(evt);
            }
        });

        acquista_quantita.setText("0");
        acquista_quantita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                acquista_quantitaKeyReleased(evt);
            }
        });

        acquista_aggiungi.setText("Aggiungi");
        acquista_aggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acquista_aggiungiActionPerformed(evt);
            }
        });

        table_scontrino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "prodotto", "quantità", "prezzo", "totale"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_scontrino);

        acquista_button.setText("Acquista");
        acquista_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acquista_buttonActionPerformed(evt);
            }
        });

        jLabel9.setText("Fornitore");

        acquista_fornitore.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        acquista_storico.setText("Visualizza Storico Acquisti");
        acquista_storico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acquista_storicoActionPerformed(evt);
            }
        });

        jLabel12.setText("Barcode");

        acquista_barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acquista_barcodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AcquistaLayout = new javax.swing.GroupLayout(Acquista);
        Acquista.setLayout(AcquistaLayout);
        AcquistaLayout.setHorizontalGroup(
            AcquistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcquistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AcquistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AcquistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(acquista_prodotto, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acquista_fornitore, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acquista_totale, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(acquista_quantita)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acquista_prezzo)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AcquistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(acquista_barcode)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(AcquistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AcquistaLayout.createSequentialGroup()
                        .addComponent(acquista_aggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(acquista_button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acquista_storico))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        AcquistaLayout.setVerticalGroup(
            AcquistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcquistaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(AcquistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acquista_storico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AcquistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AcquistaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(AcquistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acquista_button)
                            .addComponent(acquista_aggiungi))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AcquistaLayout.createSequentialGroup()
                        .addComponent(acquista_fornitore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acquista_prodotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acquista_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acquista_quantita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acquista_prezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acquista_totale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        MainMenu.addTab("Acquista", Acquista);

        table_magazzino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "prodotto", "quantità", "prezzo listino", "barcode"
            }
        ));
        mag_tabella.setViewportView(table_magazzino);

        mag_cerca.setText("Cerca nome");

        jLabel10.setText("Cerca Prodotto");

        mag_cercabarcode.setText("Cerca barcode");
        mag_cercabarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mag_cercabarcodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MagazzinoLayout = new javax.swing.GroupLayout(Magazzino);
        Magazzino.setLayout(MagazzinoLayout);
        MagazzinoLayout.setHorizontalGroup(
            MagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MagazzinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mag_tabella, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addGroup(MagazzinoLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mag_cerca, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mag_cercabarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MagazzinoLayout.setVerticalGroup(
            MagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MagazzinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mag_tabella, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MagazzinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mag_cerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(mag_cercabarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        MainMenu.addTab("Magazzino", Magazzino);

        table_fornitori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome", "indirizzo", "città", "nazione"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        forn_tabella.setViewportView(table_fornitori);

        forn_cerca.setText("Cerca nome");
        forn_cerca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                forn_cercaKeyReleased(evt);
            }
        });

        jLabel11.setText("Cerca Fornitore");

        btn_nuovofornitore.setText("Nuovo Fornitore");
        btn_nuovofornitore.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btn_nuovofornitoreComponentShown(evt);
            }
        });
        btn_nuovofornitore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuovofornitoreActionPerformed(evt);
            }
        });

        btn_agg.setText("Aggiorna");
        btn_agg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aggActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FornitoriLayout = new javax.swing.GroupLayout(Fornitori);
        Fornitori.setLayout(FornitoriLayout);
        FornitoriLayout.setHorizontalGroup(
            FornitoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FornitoriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FornitoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FornitoriLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forn_cerca, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(forn_tabella))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FornitoriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_nuovofornitore, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        FornitoriLayout.setVerticalGroup(
            FornitoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FornitoriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FornitoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuovofornitore)
                    .addComponent(btn_agg))
                .addGap(18, 18, 18)
                .addComponent(forn_tabella, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FornitoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forn_cerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainMenu.addTab("Fornitori", Fornitori);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenu, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acquista_prodottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acquista_prodottoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acquista_prodottoActionPerformed

    private void acquista_prezzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acquista_prezzoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_acquista_prezzoActionPerformed

    private void acquista_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acquista_buttonActionPerformed
        // TODO add your handling code here:
        try {
            db.aggiungiProdotto(scontrino);

        } catch (SQLException ex) {
            Logger.getLogger(NegozioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        model_s.getDataVector().removeAllElements();
        model_s.fireTableDataChanged();
        scontrino.clear();
    }//GEN-LAST:event_acquista_buttonActionPerformed

    private void vendi_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendi_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendi_buttonActionPerformed

    private void mag_cercabarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mag_cercabarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mag_cercabarcodeActionPerformed

    private void acquista_storicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acquista_storicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acquista_storicoActionPerformed

    private void vendi_storicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendi_storicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendi_storicoActionPerformed

    private void acquista_aggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acquista_aggiungiActionPerformed
        // TODO add your handling code here:
        String nome = acquista_prodotto.getText();
        String barcode = acquista_barcode.getText();
        int qnt = Integer.parseInt(acquista_quantita.getText());
        double prezzo = Double.parseDouble(acquista_prezzo.getText());
        double totale = Double.parseDouble(acquista_totale.getText());
        scontrino.add(new Prodotto(nome, qnt, prezzo, totale, barcode));
        model_s.insertRow(model_s.getRowCount(), new Object[]{nome, qnt, prezzo, totale});
    }//GEN-LAST:event_acquista_aggiungiActionPerformed

    private void acquista_prezzoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acquista_prezzoKeyPressed

    }//GEN-LAST:event_acquista_prezzoKeyPressed

    private void acquista_prezzoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acquista_prezzoKeyReleased
        // TODO add your handling code here:
        calcolo_totale();
    }//GEN-LAST:event_acquista_prezzoKeyReleased

    private void acquista_quantitaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acquista_quantitaKeyReleased
        // TODO add your handling code here:
        calcolo_totale();
    }//GEN-LAST:event_acquista_quantitaKeyReleased

    private void acquista_barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acquista_barcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acquista_barcodeActionPerformed

    private void btn_nuovofornitoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuovofornitoreActionPerformed
        // TODO add your handling code here:
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuovo_fornitore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuovo_fornitore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuovo_fornitore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuovo_fornitore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuovo_fornitore().setVisible(true);
            }
        });
    }//GEN-LAST:event_btn_nuovofornitoreActionPerformed

    private void btn_nuovofornitoreComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btn_nuovofornitoreComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuovofornitoreComponentShown

    //Campo ricerca
    private void forn_cercaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_forn_cercaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_forn_cercaKeyReleased

    private void btn_aggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aggActionPerformed
        model_f.getDataVector().removeAllElements();
        model_f.fireTableDataChanged();
        try {
            lista_fornitori();
        } catch (SQLException ex) {
            Logger.getLogger(NegozioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_aggActionPerformed

    private void vendi_aggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendi_aggiungiActionPerformed
        // TODO add your handling code here:
        model_v = (DefaultTableModel) table_vendi.getModel();
        boolean flag = true;
        String nome = vendi_nome_prodotto.getSelectedItem().toString().substring(0, vendi_nome_prodotto.getSelectedItem().toString().indexOf("("));
        ResultSet rs = db.cerca_prodotto(nome);
        double prezzo = 0;
        int qnt = Integer.parseInt(vendi_quantita.getText());
        try {
            while (rs.next()) {
                prezzo = Double.parseDouble(rs.getString("prezzo"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NegozioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        double totale = Double.parseDouble(vendi_totale.getText());

        try {
            flag = db.verifica_qt(Integer.parseInt(vendi_quantita.getText()), nome);
        } catch (SQLException ex) {
            Logger.getLogger(NegozioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (flag == false) {
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Allarme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(Allarme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(Allarme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(Allarme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Allarme().setVisible(true);
                }
            });
        } else {
            model_v.insertRow(model_v.getRowCount(), new Object[]{nome, qnt, prezzo, totale});
        }


    }//GEN-LAST:event_vendi_aggiungiActionPerformed

    private void vendi_nome_prodottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendi_nome_prodottoActionPerformed
        // TODO add your handling code here:
        //box_qnt_vendi.removeAllItems();
        estrai_qtprodotto();
        vendi_totale.setText(calcolo_totale_vendi(Integer.parseInt(box_qnt_vendi.getSelectedItem().toString()))); 
        
    }//GEN-LAST:event_vendi_nome_prodottoActionPerformed

    private void box_qnt_vendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_qnt_vendiActionPerformed
        // TODO add your handling code here:
        //String x = vendi_nome_prodotto.getSelectedItem().toString().substring(0, vendi_nome_prodotto.getSelectedItem().toString().indexOf("("));
        String a = calcolo_totale_vendi(Integer.parseInt(box_qnt_vendi.getSelectedItem().toString()));
        vendi_totale.setText(a);
        //db.aggiorna_qtprodotto(x, Integer.parseInt(box_qnt_vendi.getSelectedItem().toString()));
        //vendi_totale.setText(calcolo_totale_vendi(1));
    }//GEN-LAST:event_box_qnt_vendiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NegozioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NegozioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NegozioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NegozioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NegozioForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(NegozioForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acquista;
    private javax.swing.JPanel Fornitori;
    private javax.swing.JPanel Magazzino;
    private javax.swing.JTabbedPane MainMenu;
    private javax.swing.JPanel Vendi;
    private javax.swing.JButton acquista_aggiungi;
    private javax.swing.JTextField acquista_barcode;
    private javax.swing.JButton acquista_button;
    private javax.swing.JComboBox<String> acquista_fornitore;
    private javax.swing.JTextField acquista_prezzo;
    private javax.swing.JTextField acquista_prodotto;
    private javax.swing.JTextField acquista_quantita;
    private javax.swing.JButton acquista_storico;
    private javax.swing.JTextField acquista_totale;
    private javax.swing.JComboBox<String> box_qnt_vendi;
    private javax.swing.JButton btn_agg;
    private javax.swing.JButton btn_nuovofornitore;
    private javax.swing.JTextField forn_cerca;
    private javax.swing.JScrollPane forn_tabella;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mag_cerca;
    private javax.swing.JTextField mag_cercabarcode;
    private javax.swing.JScrollPane mag_tabella;
    private javax.swing.JTable table_fornitori;
    private javax.swing.JTable table_magazzino;
    private javax.swing.JTable table_scontrino;
    private javax.swing.JTable table_vendi;
    private javax.swing.JButton vendi_aggiungi;
    private javax.swing.JButton vendi_button;
    private javax.swing.JComboBox<String> vendi_nome_prodotto;
    private javax.swing.JButton vendi_storico;
    private javax.swing.JTextField vendi_totale;
    // End of variables declaration//GEN-END:variables
}
